"""add feature tables

Revision ID: 06ce2c7c131b
Revises: 66d724ae3305
Create Date: 2026-05-29 02:35:34.958841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06ce2c7c131b'
down_revision: Union[str, Sequence[str], None] = '66d724ae3305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_section_edits',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('section_key', sa.Text(), nullable=False),
    sa.Column('version_before', sa.Integer(), nullable=False),
    sa.Column('version_after', sa.Integer(), nullable=False),
    sa.Column('content_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('editor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('human', 'ai_rewrite', 'revert', name='edit_source'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['editor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['market_research_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('report_section_edits_history_idx', 'report_section_edits', ['report_id', 'section_key', sa.literal_column('ts DESC')], unique=False)
    op.create_table('report_sections',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('section_key', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['market_research_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'section_key', name='report_sections_report_id_section_key_key')
    )
    op.create_table('report_shares',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False),
    sa.Column('permission', sa.Enum('view', 'edit', name='share_permission'), nullable=False),
    sa.Column('granted_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['market_research_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('report_shares_active_uniq', 'report_shares', ['report_id', 'target_user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    # Backfill report_sections from existing JSONB sections
    op.execute("""
        INSERT INTO report_sections (report_id, section_key, content, version, updated_by_user_id, updated_at)
        SELECT 
            id,
            key,
            value,
            1,
            user_id,
            created_at
        FROM market_research_reports, jsonb_each(sections)
        ON CONFLICT (report_id, section_key) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('report_shares_active_uniq', table_name='report_shares', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('report_shares')
    op.drop_table('report_sections')
    op.drop_index('report_section_edits_history_idx', table_name='report_section_edits')
    op.drop_table('report_section_edits')
    sa.Enum(name='edit_source').drop(op.get_bind())
    sa.Enum(name='share_permission').drop(op.get_bind())
    # ### end Alembic commands ###
